// Descriptions for all component types - shown on hover
const descriptions = {
    // Generic
    client: 'End user device that initiates requests to the system',
    mobile: 'Mobile application client for iOS/Android platforms',
    browser: 'Web browser client that renders HTML/CSS/JS',
    loadBalancer: 'Distributes incoming traffic across multiple servers for high availability',
    webServer: 'Serves static content and handles HTTP requests (Nginx, Apache)',
    appServer: 'Runs application business logic and processes dynamic requests',
    apiGateway: 'Single entry point for APIs; handles routing, auth, rate limiting',
    reverseProxy: 'Forwards client requests to backend servers; provides caching and SSL termination',
    cache: 'In-memory data store for fast read access to frequently used data',
    redis: 'In-memory key-value store used for caching, sessions, and pub/sub',
    memcached: 'High-performance distributed memory caching system',
    database: 'Persistent data storage system for structured or unstructured data',
    sqlDb: 'Relational database using SQL for structured data with ACID compliance',
    nosqlDb: 'Non-relational database for flexible schema and horizontal scaling',
    graphDb: 'Database optimized for storing and querying graph-structured data',
    queue: 'Asynchronous message broker for decoupling services',
    kafka: 'Distributed event streaming platform for high-throughput data pipelines',
    rabbitmq: 'Message broker implementing AMQP for reliable message delivery',
    cdn: 'Content Delivery Network; caches content at edge locations globally',
    storage: 'Object storage for unstructured data like files, images, backups',
    fileStorage: 'Network file system for shared file access across servers',
    dns: 'Domain Name System; resolves domain names to IP addresses',
    firewall: 'Network security device that monitors and filters traffic based on rules',
    waf: 'Web Application Firewall; protects against XSS, SQL injection, DDoS',
    auth: 'Authentication and authorization service for identity management',
    oauth: 'OAuth 2.0 provider for delegated authorization and SSO',
    search: 'Full-text search engine for indexing and querying large datasets',
    elasticsearch: 'Distributed search and analytics engine built on Apache Lucene',
    monitoring: 'System observability tool for metrics, alerts, and dashboards',
    logging: 'Centralized log aggregation and analysis service',
    analytics: 'Data analytics platform for business intelligence and reporting',
    notification: 'Push notification service for real-time user alerts',
    email: 'Transactional and marketing email delivery service',
    sms: 'SMS messaging service for notifications and 2FA',
    scheduler: 'Job scheduler for running tasks at specified intervals',
    worker: 'Background worker process for async task execution',
    microservice: 'Small, independently deployable service focused on a single business capability',
    serverless: 'Function-as-a-Service; runs code without managing servers',
    container: 'Lightweight, portable runtime environment using Docker/OCI',
    vm: 'Virtual Machine; full OS-level virtualization on shared hardware',

    // AWS
    ec2: 'AWS Elastic Compute Cloud; scalable virtual servers in the cloud',
    lambda: 'AWS serverless compute; runs code in response to events',
    ecs: 'AWS Elastic Container Service; Docker container orchestration',
    eks: 'AWS Elastic Kubernetes Service; managed Kubernetes clusters',
    fargate: 'AWS serverless compute engine for containers (no EC2 management)',
    beanstalk: 'AWS PaaS for deploying web apps without infrastructure management',
    batch: 'AWS Batch; runs batch computing workloads on managed infrastructure',
    lightsail: 'AWS simplified VPS for small-scale applications',
    s3: 'AWS Simple Storage Service; scalable object storage with 99.999999999% durability',
    ebs: 'AWS Elastic Block Store; persistent block storage for EC2',
    efs: 'AWS Elastic File System; managed NFS for EC2 instances',
    glacier: 'AWS low-cost archive storage for long-term data retention',
    fsx: 'AWS managed file systems (Windows, Lustre, NetApp, OpenZFS)',
    rds: 'AWS Relational Database Service; managed SQL databases',
    dynamodb: 'AWS fully managed NoSQL database with single-digit ms latency',
    aurora: 'AWS MySQL/PostgreSQL-compatible relational database with 5x performance',
    redshift: 'AWS data warehouse for petabyte-scale analytics',
    elasticache: 'AWS managed Redis/Memcached for in-memory caching',
    neptune: 'AWS managed graph database for highly connected datasets',
    documentdb: 'AWS managed MongoDB-compatible document database',
    keyspaces: 'AWS managed Apache Cassandra-compatible database',
    timestream: 'AWS serverless time-series database for IoT and operational data',
    vpc: 'AWS Virtual Private Cloud; isolated network environment containing subnets, route tables, and security groups',
    subnet: 'A range of IP addresses in a VPC; can be public (internet-facing) or private (internal only)',
    elb: 'AWS Elastic Load Balancer; distributes traffic across targets (ALB/NLB/CLB)',
    nlb: 'AWS Network Load Balancer; ultra-low latency Layer 4 load balancing',
    cloudfront: 'AWS CDN; delivers content with low latency from 400+ edge locations',
    route53: 'AWS DNS service with health checking and traffic routing',
    'apigateway-aws': 'AWS API Gateway; create, publish, and manage APIs at any scale',
    directConnect: 'AWS dedicated network connection from on-premises to AWS',
    globalAccelerator: 'AWS Global Accelerator; improves availability via AWS global network',
    transitGateway: 'AWS Transit Gateway; connects VPCs and on-premises networks',
    sqs: 'AWS Simple Queue Service; fully managed message queuing',
    sns: 'AWS Simple Notification Service; pub/sub messaging and mobile notifications',
    eventbridge: 'AWS EventBridge; serverless event bus for event-driven architectures',
    kinesis: 'AWS Kinesis; real-time data streaming for analytics and ML',
    msk: 'AWS Managed Streaming for Apache Kafka',
    mq: 'AWS managed message broker for ActiveMQ and RabbitMQ',
    stepFunctions: 'AWS Step Functions; visual workflow orchestration for distributed apps',
    cognito: 'AWS Cognito; user sign-up, sign-in, and access control',
    iam: 'AWS Identity and Access Management; fine-grained access control',
    kms: 'AWS Key Management Service; create and manage encryption keys',
    secretsManager: 'AWS Secrets Manager; rotate, manage, and retrieve secrets',
    'waf-aws': 'AWS WAF; protects web apps from common exploits',
    shield: 'AWS Shield; managed DDoS protection',
    guardduty: 'AWS GuardDuty; intelligent threat detection using ML',
    inspector: 'AWS Inspector; automated security assessment for EC2 and containers',
    macie: 'AWS Macie; discovers and protects sensitive data in S3',
    athena: 'AWS Athena; serverless interactive SQL queries on S3 data',
    emr: 'AWS EMR; managed Hadoop/Spark for big data processing',
    glue: 'AWS Glue; serverless ETL for data preparation and cataloging',
    quicksight: 'AWS QuickSight; serverless BI dashboards and visualizations',
    sagemaker: 'AWS SageMaker; build, train, and deploy ML models at scale',
    comprehend: 'AWS Comprehend; NLP service for text analysis',
    rekognition: 'AWS Rekognition; image and video analysis using deep learning',
    polly: 'AWS Polly; text-to-speech service with lifelike voices',
    lex: 'AWS Lex; conversational AI for chatbots (powers Alexa)',
    bedrock: 'AWS Bedrock; foundation models from AI21, Anthropic, Meta, etc.',
    cloudwatch: 'AWS CloudWatch; monitoring, logging, and alerting for AWS resources',
    cloudtrail: 'AWS CloudTrail; audit trail of API calls across your AWS account',
    config: 'AWS Config; tracks resource configurations and compliance',
    systemsManager: 'AWS Systems Manager; operational management for AWS resources',
    cloudformation: 'AWS CloudFormation; infrastructure as code using templates',
    ses: 'AWS Simple Email Service; scalable email sending and receiving',
    pinpoint: 'AWS Pinpoint; targeted push notifications and campaign management',
    amplify: 'AWS Amplify; full-stack framework for web and mobile apps',
    appsync: 'AWS AppSync; managed GraphQL API with real-time data sync',
    codepipeline: 'AWS CodePipeline; CI/CD pipeline for automated releases',
    codebuild: 'AWS CodeBuild; fully managed build service',
    codecommit: 'AWS CodeCommit; managed Git source control',

    // OpenShift / K8s
    pod: 'Smallest deployable unit in Kubernetes; runs one or more containers',
    deployment: 'Manages ReplicaSets and provides declarative updates for Pods',
    deploymentConfig: 'OpenShift-specific deployment strategy with triggers and hooks',
    statefulset: 'Manages stateful applications with stable network IDs and persistent storage',
    daemonset: 'Ensures a Pod runs on all (or selected) nodes in the cluster',
    replicaset: 'Maintains a stable set of replica Pods running at any given time',
    job: 'Creates Pods that run to completion for batch processing',
    cronjob: 'Runs Jobs on a time-based schedule (cron syntax)',
    service: 'Stable network endpoint that routes traffic to a set of Pods',
    route: 'OpenShift Route; exposes a Service externally via hostname',
    ingress: 'Manages external HTTP/HTTPS access to Services in a cluster',
    networkPolicy: 'Controls network traffic flow between Pods using rules',
    egressIP: 'Assigns a fixed source IP for outbound traffic from Pods',
    configmap: 'Stores non-confidential configuration data as key-value pairs',
    secret: 'Stores sensitive data like passwords, tokens, and keys',
    pvc: 'Persistent Volume Claim; requests storage resources from the cluster',
    pv: 'Persistent Volume; a piece of storage provisioned by an admin',
    storageClass: 'Defines storage types and provisioning policies for PVs',
    hpa: 'Horizontal Pod Autoscaler; scales Pods based on CPU/memory metrics',
    vpa: 'Vertical Pod Autoscaler; adjusts Pod resource requests automatically',
    namespace: 'Virtual cluster partition for resource isolation and access control',
    project: 'OpenShift Project; namespace with additional metadata and policies',
    resourceQuota: 'Limits aggregate resource consumption per namespace',
    limitRange: 'Sets default and max resource limits for containers in a namespace',
    buildConfig: 'OpenShift BuildConfig; defines how to build container images',
    imageStream: 'OpenShift ImageStream; tracks container image versions',
    template: 'OpenShift Template; parameterized set of resources to create',
    serviceAccount: 'Identity for processes running in Pods; used for RBAC',
    role: 'Defines a set of permissions within a namespace',
    roleBinding: 'Grants Role permissions to users or ServiceAccounts',
    scc: 'Security Context Constraints; controls Pod security in OpenShift',
    operator: 'Custom controller that extends Kubernetes API for app management',
    csv: 'ClusterServiceVersion; describes an Operator version and its requirements',
    subscription: 'Subscribes to an Operator catalog for automatic updates',

    // GCP
    computeEngine: 'GCP virtual machines with custom or predefined machine types',
    cloudFunctions: 'GCP serverless functions triggered by events or HTTP',
    cloudRun: 'GCP fully managed serverless container platform',
    gke: 'Google Kubernetes Engine; managed Kubernetes clusters',
    appEngine: 'GCP PaaS for building scalable web apps and APIs',
    cloudStorage: 'GCP unified object storage with global edge caching',
    persistentDisk: 'GCP block storage for Compute Engine VMs',
    filestore: 'GCP managed NFS file storage for applications',
    cloudSQL: 'GCP managed MySQL, PostgreSQL, and SQL Server databases',
    cloudSpanner: 'GCP globally distributed, strongly consistent relational database',
    bigtable: 'GCP NoSQL wide-column database for large analytical workloads',
    firestore: 'GCP serverless NoSQL document database with real-time sync',
    memorystore: 'GCP managed Redis and Memcached for in-memory caching',
    cloudLoadBalancing: 'GCP global and regional load balancing for all traffic types',
    cloudCDN: 'GCP content delivery network using Google edge infrastructure',
    cloudDNS: 'GCP scalable, reliable DNS hosting service',
    cloudArmor: 'GCP DDoS protection and WAF for applications',
    cloudVPN: 'GCP secure connection between on-premises and GCP via IPsec',
    pubsub: 'GCP Pub/Sub; global messaging and event ingestion service',
    cloudTasks: 'GCP managed task queue for asynchronous task execution',
    cloudScheduler: 'GCP fully managed cron job scheduler',
    workflows: 'GCP serverless workflow orchestration for HTTP-based services',
    bigquery: 'GCP serverless data warehouse for SQL analytics at petabyte scale',
    dataflow: 'GCP managed Apache Beam for stream and batch data processing',
    dataproc: 'GCP managed Spark and Hadoop clusters for big data',
    vertexAI: 'GCP unified ML platform for building and deploying models',
    visionAI: 'GCP pre-trained models for image analysis and classification',
    cloudIAM: 'GCP Identity and Access Management for fine-grained permissions',
    secretManager: 'GCP secure storage for API keys, passwords, and certificates',
    cloudKMS: 'GCP Cloud Key Management Service for encryption key lifecycle',
    cloudMonitoring: 'GCP monitoring for metrics, uptime checks, and alerting',
    cloudLogging: 'GCP centralized log management and analysis',
    cloudBuild: 'GCP CI/CD platform for building, testing, and deploying',
    firebase: 'Google platform for building mobile and web applications',
    firebaseAuth: 'Firebase Authentication; email, social, and phone sign-in',
    firebaseHosting: 'Firebase Hosting; fast and secure static web hosting',

    // Azure
    azureVM: 'Azure Virtual Machines; on-demand scalable compute resources',
    azureFunctions: 'Azure serverless compute triggered by events or HTTP',
    aks: 'Azure Kubernetes Service; managed Kubernetes clusters',
    appService: 'Azure PaaS for hosting web apps, REST APIs, and mobile backends',
    containerInstances: 'Azure serverless containers without orchestration overhead',
    containerApps: 'Azure managed serverless container platform with auto-scaling',
    batchAzure: 'Azure Batch; large-scale parallel and HPC batch jobs',
    blobStorage: 'Azure Blob Storage; massively scalable object storage',
    azureFiles: 'Azure Files; managed file shares accessible via SMB/NFS',
    diskStorage: 'Azure managed disks for VMs with high availability',
    dataLake: 'Azure Data Lake Storage; big data analytics storage',
    azureSQL: 'Azure SQL Database; fully managed relational database engine',
    cosmosDB: 'Azure Cosmos DB; globally distributed multi-model NoSQL database',
    azureCache: 'Azure Cache for Redis; in-memory data store',
    azurePostgres: 'Azure Database for PostgreSQL; managed PostgreSQL service',
    azureMySQL: 'Azure Database for MySQL; managed MySQL service',
    azureLB: 'Azure Load Balancer; Layer 4 load balancing for high availability',
    appGateway: 'Azure Application Gateway; Layer 7 load balancer with WAF',
    frontDoor: 'Azure Front Door; global load balancer with CDN and WAF',
    azureCDN: 'Azure CDN; global content delivery with Microsoft edge network',
    azureDNS: 'Azure DNS; host DNS domains on Azure infrastructure',
    trafficManager: 'Azure Traffic Manager; DNS-based traffic load balancer',
    vnet: 'Azure Virtual Network; isolated network for Azure resources',
    expressRoute: 'Azure ExpressRoute; private connection from on-premises to Azure',
    serviceBus: 'Azure Service Bus; enterprise message broker with queues and topics',
    eventHub: 'Azure Event Hubs; big data streaming platform for millions of events/sec',
    eventGrid: 'Azure Event Grid; reactive event routing for event-driven architectures',
    queueStorage: 'Azure Queue Storage; simple message queuing for large workloads',
    logicApps: 'Azure Logic Apps; automated workflows for app and data integration',
    azureAD: 'Azure Active Directory; identity and access management service',
    keyVault: 'Azure Key Vault; safeguard cryptographic keys and secrets',
    azureWAF: 'Azure WAF; centralized web application protection',
    ddosProtection: 'Azure DDoS Protection; always-on traffic monitoring and mitigation',
    sentinel: 'Azure Sentinel; cloud-native SIEM and SOAR platform',

    synapse: 'Azure Synapse Analytics; unified analytics for data warehousing and big data',
    databricks: 'Azure Databricks; Apache Spark-based analytics platform',
    streamAnalytics: 'Azure Stream Analytics; real-time data stream processing',
    azureML: 'Azure Machine Learning; end-to-end ML lifecycle management',
    cognitiveServices: 'Azure Cognitive Services; pre-built AI APIs for vision, speech, language',
    azureOpenAI: 'Azure OpenAI Service; access to GPT, DALL-E, and Codex models',
    azureMonitor: 'Azure Monitor; full-stack monitoring for applications and infrastructure',
    appInsights: 'Azure Application Insights; APM for live web applications',
    logAnalytics: 'Azure Log Analytics; query and analyze log data',
    azureDevOps: 'Azure DevOps; CI/CD pipelines, repos, boards, and artifacts',

    // Databases
    postgresql: 'Open-source relational database known for extensibility and SQL compliance',
    mysql: 'Popular open-source relational database for web applications',
    mariadb: 'Community-developed fork of MySQL with enhanced features',
    oracle: 'Enterprise relational database with advanced features and PL/SQL',
    sqlserver: 'Microsoft SQL Server; enterprise relational database with BI tools',
    mongodb: 'Document-oriented NoSQL database with flexible JSON-like schema',
    cassandra: 'Distributed wide-column NoSQL database for high availability',
    couchdb: 'Document database with HTTP API and multi-master replication',
    neo4j: 'Native graph database for connected data and relationship queries',
    influxdb: 'Time-series database optimized for metrics, events, and IoT data',
    clickhouse: 'Column-oriented OLAP database for real-time analytical queries',
    cockroachdb: 'Distributed SQL database with automatic sharding and strong consistency',
    tidb: 'Distributed SQL database compatible with MySQL protocol',
    vitess: 'Database clustering system for horizontal scaling of MySQL',
    etcd: 'Distributed key-value store for shared configuration and service discovery',
    consul: 'Service mesh and key-value store for service discovery and config',
    zookeeper: 'Centralized service for distributed coordination and configuration',
};

export default descriptions;
